#!/usr/bin/env node
/*
 *********************************************************************************
 *                     Copyright (C) 2018 wystan
 *
 *       filename: crawler.js
 *    description:
 *        created: 2018-04-13 20:04:23
 *         author: wystan
 *
 *********************************************************************************
 */

const request = require("request");
const emitter = require("./emitter");
const maxconn = 10;

let url="http://ip.taobao.com/service/getIpInfo.php?ip=";
let emit = emitter();
let first = 1;
let a = 1;
let b = 1;
let c = 1;
let d = 1;

function crawle(addr) {
    request(url+addr, (err, res, body)=>{
        if (err != null) {
            console.error("error on :", addr);
            console.error(err);
            emit.aemit("crawle", addr);
            return;
        }
        let rst = JSON.parse(body);
        if (rst.code === 0) {
            let record = "";
            for (let attr in rst.data) {
                record = record + rst.data[attr] + "|";
            }
            if (first) {
                first = 0;
                let header = "";
                for (let attr in rst.data) {
                    header = header + attr + "|";
                }
                console.log(header);
            }
            console.log(record);
            trigger();
        } else {
            console.warn("fail on", addr);
            emit.aemit("crawle", addr);
        }
    });
}

function get_next() {
    if (c > 255) {
        b++;
        c = d = 1;
    }
    if (b > 255) {
        a++;
        b = c = d = 1;
    }
    if (a > 255) {
        return null;
    }
    return a + "." + b + "." + c++ + "." + d;
}

function trigger() {
    let next = get_next();
    if (next) {
        emit.aemit("crawle", next);
    }
}

function main() {
    emit.on("crawle", crawle.bind(null));
    for (let i=0; i<maxconn; i++) {
        trigger();
    }
}

/************************************* END **************************************/
main();
